jobs:
  build:
    # ... (your existing build job)

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Arcot-Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/requirements_ml.txt

      - name: Run ML Service
        run: |
          echo "Current Directory: $(pwd)"
          echo "Contents of the Directory: $(ls -al)"
          python ${{ github.workspace }}/run_ml_service.py
